services:
  auth_db:
    image: postgres:16-alpine
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: pass
    volumes:
      - auth_db:/var/lib/postgres
    ports:
      - 5555:5432
    networks:
      - auth_network

  auth_pgadmin:
    image: dpage/pgadmin4
    container_name: auth_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    volumes:
      - auth_pg_admin:/var/lib/pgadmin
    networks:
      - auth_network

volumes:
  auth_db:
    external: false
  auth_pg_admin:
    external: false

networks:
  auth_network:
    driver: bridge
    external: false
