services:
  auth_db:
    image: postgres:16-alpine
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: pass
    volumes:
      - auth_db:/var/lib/postgres
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 5555:5432
    networks:
      - auth_network

  auth_pgadmin:
    image: dpage/pgadmin4
    container_name: auth_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    volumes:
      - auth_pg_admin:/var/lib/pgadmin
    networks:
      - auth_network

  auth_service:
    image: kunmhing/authservice:latest
    container_name: auth_service
    environment:
      - DATABASE_URL=postgres://user:pass@auth_db:5432/auth_db
      - JWT_SECRET=${JWT_SECRET}
      - CMU_OAUTH_CLIENT_ID=${CMU_OAUTH_CLIENT_ID}
      - CMU_OAUTH_CLIENT_SECRET=${CMU_OAUTH_CLIENT_SECRET}
      - CMU_OAUTH_GET_TOKEN_URL=${CMU_OAUTH_GET_TOKEN_URL}
      - CMU_OAUTH_GET_BASIC_INFO=${CMU_OAUTH_GET_BASIC_INFO}
      - CMU_OAUTH_REDIRECT_URL=${CMU_OAUTH_REDIRECT_URL}
    ports:
      - 3002:3002
    networks:
      - auth_network
volumes:
  auth_db:
    external: false
  auth_pg_admin:
    external: false

networks:
  auth_network:
    driver: bridge
    external: false
